name: Automated API Tests Using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create directory for reports
        run: mkdir -p TestArtifact

      # Install Node.js on the runner
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Use the latest LTS version of Node.js

      # Install Newman globally and required reporters
      - name: Install Newman and reporters
        run: |
          npm install -g newman@5 # Latest version of Newman
          npm install -g newman-reporter-html@1.0.3 # Use a stable version that is available

      # Install Postman CLI
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Login to Postman CLI
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Run API tests using Postman CLI
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/EDA.json" --reporters cli,html --reporter-html-export TestArtifact/htmlreport.html
        continue-on-error: true

      # Upload the report to TestArtifact directory
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: TestArtifact
